### ISSUE TITLE
Method Jackiedo\LogReader\Console\Commands\LogReaderGetCommand::handle() does not exist

### ISSUE THREAD

**Issue by enkeli** [JackieDo/Laravel-Log-Reader#24]
The artisan command does not work in laravel 5.5, i guess this part isn't updated to work with laravel 5?

**Comment by sangnguyenplus** [comment]
@JackieDo,

Just need to change the method name of commands from `fire` to `handle` then it will work on Laravel 5.5.

**Comment by JackieDo** [comment]
> The artisan command does not work in laravel 5.5, i guess this part isn't updated to work with laravel 5?

@enkeli : Fixed it on commit [10c6b52](https://github.com/JackieDo/Laravel-Log-Reader/commit/10c6b52b52cde4250e40bae83d7a17f0532adfc2) and put this commit into release 2.1.1
