### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by ttimot24** [JackieDo/Laravel-Log-Reader#28]
Currently can't install Laravel 6. Can you please look into it and add support for it?

>  Problem 1
    - jackiedo/log-reader 1.0.9 requires illuminate/console 4.2 -> no matching package found.
    - Conclusion: don't install laravel/framework v6.9.0

**Comment by patrickvlt-old** [comment]
That's a shame. This looked really useful

**Comment by paulmartimx** [comment]
+1

I cloned the repo locally, and the code works perfectly in Laravel 6, it's just a composer.json conflict.

Could you update the composer.json?  It is a very useful package and, with a very little edit, we could keep using it...

**Comment by JackieDo** [comment]
@ttimot24 @43874 @paulmartimx : Yes, I am upgrading all my packages to be compatible with the new Laravel versions. This will take several days. Hope you wait.

**Comment by paulmartimx** [comment]
Good to know @JackieDo , thanks!

Just to know: I tested the package in fresh Laravel v7.4.0 ... is working fine too.

**Comment by JackieDo** [comment]
@ttimot24 , @43874 , @paulmartimx : I have upgraded this package to be compatible with new versions of Laravel.
- Support Laravel 6.x: pull request #32 
- Support Laravel 7.x: pull request #33 

And the [latest release](https://github.com/JackieDo/Laravel-Log-Reader/releases/latest) contains all of these pull requests.
