### ISSUE TITLE
LogReader error

### ISSUE THREAD

**Issue by Simoneu01** [JackieDo/Laravel-Log-Reader#36]
PHP Version: 8.1
Laravel: 8

`[2022-01-15 23:48:57] testing.WARNING: class_exists(): Passing null to parameter #1 ($class) of type string is deprecated in /home/simo/code/vendor/jackiedo/log-reader/src/Jackiedo/LogReader/LogReader.php on line 133  `

Referencing this line:
https://github.com/JackieDo/Laravel-Log-Reader/blob/01faa9dc4470ddf2d5b085a55cc2f0dca70f225c/src/Jackiedo/LogReader/LogReader.php#L133

**Comment by JackieDo** [comment]
> PHP Version: 8.1 Laravel: 8
> 
> `[2022-01-15 23:48:57] testing.WARNING: class_exists(): Passing null to parameter #1 ($class) of type string is deprecated in /home/simo/code/vendor/jackiedo/log-reader/src/Jackiedo/LogReader/LogReader.php on line 133 `
> 
> Referencing this line:
> 
> https://github.com/JackieDo/Laravel-Log-Reader/blob/01faa9dc4470ddf2d5b085a55cc2f0dca70f225c/src/Jackiedo/LogReader/LogReader.php#L133

Fixed by pull request #39, #40 (included in release [2.2.0](https://github.com/JackieDo/Laravel-Log-Reader/releases/tag/2.2.0))
