### ISSUE TITLE
Support for Laravel 9

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [JackieDo/Laravel-Log-Reader#37]
Support for Laravel 9

**Comment by sisnox** [comment]
I'm also waiting
will it be updated?

**Comment by JackieDo** [comment]
> I'm also waiting will it be updated?

Yes, It's true.

**Comment by JackieDo** [comment]
@MrAhmedSayedAli, @sisnox:

This package now supports Laravel 9.x (PR #41) and included in the release [2.2.1](https://github.com/JackieDo/Laravel-Log-Reader/releases/tag/2.2.1)

**Comment by sisnox** [comment]
Thx good job
