### ISSUE TITLE
Please, don't use GLOB_BRACE

### ISSUE THREAD

**Issue by yvoitenko** [JackieDo/Laravel-Log-Reader#46]
Please, refactor the `LogReader` class and remove the `GLOB_BRACE` usage due to inability of using the package on Alpine containers. Thanks!

**Comment by lcabre** [comment]
Hi, in Zend Framework it has been solved like this:

`defined('GLOB_BRACE') ? GLOB_BRACE : 0`

Here is the PR https://github.com/zendframework/zend-stdlib/pull/59

**Comment by JackieDo** [comment]
@yvoitenko :
This issue was fixed in commit **c5bfb0f361383089934cd4059d7a37b9c2640609** and released in release **[2.3.0](https://github.com/JackieDo/Laravel-Log-Reader/releases/tag/2.3.0)**
